# Generated by Django 3.1 on 2020-08-09 16:02

import backend.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shape'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sphere',
        ),
        migrations.AddField(
            model_name='shape',
            name='type',
            field=models.IntegerField(choices=[(backend.constants.SHAPE_TYPES['SPHERE'], 'Sphere'), (backend.constants.SHAPE_TYPES['CUBE'], 'Cube')], default=1),
            preserve_default=False,
        ),
    ]
