# Generated by Django 3.0.8 on 2020-07-10 09:17

from django.db import migrations, models
import django.db.models.deletion

from backend.models import Shape


def insertdata(apps, schema_editor):
    Shape(type=1,color = '00ff00', attributes={'radius': 1}).save()

    Shape(type=1,color = 'ffff00', attributes={'radius': 1}).save()

    Shape(type=1, color='40ffff', attributes={'radius': 1}).save()

    Shape(type=1,color = '0000ff', attributes={'radius': 2}).save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200809_1602'),
    ]

    operations = [
        migrations.RunPython(insertdata),
    ]
